name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: create Github Release
        uses: softprops/actions-gh-release@v1
        with:
          body_path: CHANGELOG.md